/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

(* top =  1  *)
(* src = "simple.v:1" *)
module simple(a, b, c, d);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "simple.v:2" *)
  input a;
  (* src = "simple.v:2" *)
  input b;
  (* src = "simple.v:2" *)
  input c;
  (* src = "simple.v:3" *)
  output d;
  NOT _13_ (
    .A(_05_),
    .Y(_08_)
  );
  NOT _14_ (
    .A(_06_),
    .Y(_09_)
  );
  NAND _15_ (
    .A(_09_),
    .B(_08_),
    .Y(_10_)
  );
  NAND _16_ (
    .A(_06_),
    .B(_05_),
    .Y(_12_)
  );
  NAND _17_ (
    .A(_12_),
    .B(_10_),
    .Y(_11_)
  );
  assign _05_ = c;
  assign _06_ = b;
  assign _07_ = a;
  assign d = _11_;
endmodule
